version: "2"

services:
  bitmex-delta-server:
    container_name: bitmex-delta-server
    build: 
      context: .
    environment:
      - DEBUG=BitMEX:* node index.js
      - PORT=4444
      - IS_TESTNET=true
      - SYMBOL=XBTUSD,ETHUSD
      - STREAMS=quote,trade
      - BITMEX_KEY=
      - BITMEX_SECRET_KEY=
      - MAX_TABLE_LEN=5000
    ports:
      - "4444:4444"
