version: "2020.3.23"

services:
  bitmex-delta-server:
    container_name: bitmex-delta-server
    build: 
      context: .
    environment:
      - DEBUG=BitMEX:* node index.js
      - PORT=4444
      - IS_TESTNET=false
      - SYMBOL=XBTUSD,ETHUSD
      - STREAMS=orderBookL2,trade
      #// Available streams:
      #// Public:
      #// instrument,orderBookL2,quote,trade
      #// Private:
      #// execution,margin,order,position
      
      # - BITMEX_KEY= # assuming set BITMEX_KEY in .env, TEST_BITMEX_KEY as well
      # - BITMEX_SECRET_KEY= # assuming set BITMEX_SECRET_KEY in .env, TEST_BITMEX_SECRET_KEY as well
      - MAX_TABLE_LEN=5000
    env_file: .env
    ports:
      - "0:4444"
