#!/bin/bash
if [ -z "$IS_TESTNET" ]; then
  echo "Environment variable 'IS_TESTNET' is empty."
  echo "IS_TESTNET is set false."
  export IS_TESTNET=false
fi
if [ -z "$PORT" ]; then
  echo "Environment variable 'PORT' is empty!"
  echo "PORT is set to 4444."
  export PORT=4444
fi
if [ -z "$SYMBOL" ]; then
  echo "Environment variable 'SYMBOL' is empty!"
  echo "SYMBOL is set to XBTUSD."
  export SYMBOL=XBTUSD
fi
if [ -z "$STREAMS" ]; then
  echo "Environment variable 'STREAMS' is empty!"
  echo "STREAMS is set to instrument."
  export STREAMS=instrument
fi
if [ -z "$MAX_TABLE_LEN" ]; then
  echo "Environment variable 'MAX_TABLE_LEN' is empty!"
  echo "'MAX_TABLE_LEN' is set to 5000."
  export MAX_TABLE_LEN=5000
fi

if "$IS_TESTNET" = "true"; then
  export BITMEX_KEY=$TEST_BITMEX_KEY
  export BITMEX_SECRET_KEY=$TEST_BITMEX_SECRET_KEY
fi

cat config.js.template | envsubst > config.js
